<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WKMGB7594573" failures="1" tests="9" name="restapitest" time="23.958" errors="0" timestamp="24 May 2019 09:34:26 GMT">
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkResponseBoday" time="0.004"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkStatusLine" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.TC002_Get_Single_Employees" name="checkResponseBoday" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.TC002_Get_Single_Employees" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.TC002_Get_Single_Employees" name="checkStatusLine" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.TC003_Post_Employee_Record" name="checkResponseBody" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testCases.TC003_Post_Employee_Record.checkResponseBody(TC003_Post_Employee_Record.java:55)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapi.testCases.TC004_Put_Employee" name="checkStatusCode" time="0.0"/>
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="checkResponseBody" time="0.002"/>
</testsuite> <!-- restapitest -->
